// Mocks generated by Mockito 5.4.6 from annotations
// in agnovat_w/test/shift_notes_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:agnovat_w/data/models/activity.dart' as _i5;
import 'package:agnovat_w/data/models/client.dart' as _i4;
import 'package:agnovat_w/data/models/goal.dart' as _i6;
import 'package:agnovat_w/data/models/shift_note.dart' as _i7;
import 'package:agnovat_w/data/models/user.dart' as _i2;
import 'package:agnovat_w/data/services/mcp_api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardData_1 extends _i1.SmartFake implements _i3.DashboardData {
  _FakeDashboardData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientSummary_2 extends _i1.SmartFake implements _i3.ClientSummary {
  _FakeClientSummary_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_3 extends _i1.SmartFake implements _i4.Client {
  _FakeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActivity_4 extends _i1.SmartFake implements _i5.Activity {
  _FakeActivity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoal_5 extends _i1.SmartFake implements _i6.Goal {
  _FakeGoal_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShiftNote_6 extends _i1.SmartFake implements _i7.ShiftNote {
  _FakeShiftNote_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [McpApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMcpApiService extends _i1.Mock implements _i3.McpApiService {
  MockMcpApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.User> getCurrentUser({required String? clerkId}) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [], {#clerkId: clerkId}),
            returnValue: _i8.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#getCurrentUser, [], {#clerkId: clerkId}),
              ),
            ),
          )
          as _i8.Future<_i2.User>);

  @override
  _i8.Future<_i2.User> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i8.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getUserById, [userId])),
            ),
          )
          as _i8.Future<_i2.User>);

  @override
  _i8.Future<List<_i2.User>> listUsers({
    String? role,
    bool? active,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listUsers, [], {
              #role: role,
              #active: active,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<_i2.User>>.value(<_i2.User>[]),
          )
          as _i8.Future<List<_i2.User>>);

  @override
  _i8.Future<_i2.User> getUserProfile({required String? clerkId}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [], {#clerkId: clerkId}),
            returnValue: _i8.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#getUserProfile, [], {#clerkId: clerkId}),
              ),
            ),
          )
          as _i8.Future<_i2.User>);

  @override
  _i8.Future<_i2.User> syncUserFromClerk({
    required String? clerkId,
    required String? email,
    required String? name,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserFromClerk, [], {
              #clerkId: clerkId,
              #email: email,
              #name: name,
              #imageUrl: imageUrl,
            }),
            returnValue: _i8.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#syncUserFromClerk, [], {
                  #clerkId: clerkId,
                  #email: email,
                  #name: name,
                  #imageUrl: imageUrl,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.User>);

  @override
  _i8.Future<_i2.User> updateUserProfile({
    required String? clerkId,
    String? name,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #clerkId: clerkId,
              #name: name,
              #imageUrl: imageUrl,
            }),
            returnValue: _i8.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #clerkId: clerkId,
                  #name: name,
                  #imageUrl: imageUrl,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.User>);

  @override
  _i8.Future<void> updateLastLogin(String? clerkId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [clerkId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<dynamic>> listStakeholders({
    String? role,
    bool? active,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listStakeholders, [], {
              #role: role,
              #active: active,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<_i3.DashboardData> getDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, []),
            returnValue: _i8.Future<_i3.DashboardData>.value(
              _FakeDashboardData_1(this, Invocation.method(#getDashboard, [])),
            ),
          )
          as _i8.Future<_i3.DashboardData>);

  @override
  _i8.Future<_i3.ClientSummary> getClientSummary(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#getClientSummary, [clientId]),
            returnValue: _i8.Future<_i3.ClientSummary>.value(
              _FakeClientSummary_2(
                this,
                Invocation.method(#getClientSummary, [clientId]),
              ),
            ),
          )
          as _i8.Future<_i3.ClientSummary>);

  @override
  _i8.Future<List<_i4.Client>> listClients({
    bool? active,
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listClients, [], {
              #active: active,
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<_i4.Client>>.value(<_i4.Client>[]),
          )
          as _i8.Future<List<_i4.Client>>);

  @override
  _i8.Future<_i4.Client> getClient(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [clientId]),
            returnValue: _i8.Future<_i4.Client>.value(
              _FakeClient_3(this, Invocation.method(#getClient, [clientId])),
            ),
          )
          as _i8.Future<_i4.Client>);

  @override
  _i8.Future<List<_i4.Client>> searchClients(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchClients, [searchTerm]),
            returnValue: _i8.Future<List<_i4.Client>>.value(<_i4.Client>[]),
          )
          as _i8.Future<List<_i4.Client>>);

  @override
  _i8.Future<List<_i5.Activity>> listActivities({
    String? clientId,
    String? stakeholderId,
    String? activityType,
    String? status,
    String? goalId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listActivities, [], {
              #clientId: clientId,
              #stakeholderId: stakeholderId,
              #activityType: activityType,
              #status: status,
              #goalId: goalId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<_i5.Activity>>.value(<_i5.Activity>[]),
          )
          as _i8.Future<List<_i5.Activity>>);

  @override
  _i8.Future<_i5.Activity> getActivity(String? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivity, [activityId]),
            returnValue: _i8.Future<_i5.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#getActivity, [activityId]),
              ),
            ),
          )
          as _i8.Future<_i5.Activity>);

  @override
  _i8.Future<List<_i6.Goal>> listGoals({
    String? clientId,
    String? status,
    String? category,
    bool? archived,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listGoals, [], {
              #clientId: clientId,
              #status: status,
              #category: category,
              #archived: archived,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<_i6.Goal>>.value(<_i6.Goal>[]),
          )
          as _i8.Future<List<_i6.Goal>>);

  @override
  _i8.Future<_i6.Goal> getGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getGoal, [goalId]),
            returnValue: _i8.Future<_i6.Goal>.value(
              _FakeGoal_5(this, Invocation.method(#getGoal, [goalId])),
            ),
          )
          as _i8.Future<_i6.Goal>);

  @override
  _i8.Future<_i5.Activity> createActivity({
    required String? clientId,
    String? stakeholderId,
    required String? title,
    String? description,
    required _i5.ActivityType? activityType,
    _i5.ActivityStatus? status,
    List<String>? goalIds,
    String? outcomeNotes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createActivity, [], {
              #clientId: clientId,
              #stakeholderId: stakeholderId,
              #title: title,
              #description: description,
              #activityType: activityType,
              #status: status,
              #goalIds: goalIds,
              #outcomeNotes: outcomeNotes,
            }),
            returnValue: _i8.Future<_i5.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#createActivity, [], {
                  #clientId: clientId,
                  #stakeholderId: stakeholderId,
                  #title: title,
                  #description: description,
                  #activityType: activityType,
                  #status: status,
                  #goalIds: goalIds,
                  #outcomeNotes: outcomeNotes,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Activity>);

  @override
  _i8.Future<_i5.Activity> updateActivity({
    required String? activityId,
    String? title,
    String? description,
    _i5.ActivityType? activityType,
    _i5.ActivityStatus? status,
    List<String>? goalIds,
    String? outcomeNotes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateActivity, [], {
              #activityId: activityId,
              #title: title,
              #description: description,
              #activityType: activityType,
              #status: status,
              #goalIds: goalIds,
              #outcomeNotes: outcomeNotes,
            }),
            returnValue: _i8.Future<_i5.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#updateActivity, [], {
                  #activityId: activityId,
                  #title: title,
                  #description: description,
                  #activityType: activityType,
                  #status: status,
                  #goalIds: goalIds,
                  #outcomeNotes: outcomeNotes,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Activity>);

  @override
  _i8.Future<_i7.ShiftNote> getShiftNote(String? shiftNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#getShiftNote, [shiftNoteId]),
            returnValue: _i8.Future<_i7.ShiftNote>.value(
              _FakeShiftNote_6(
                this,
                Invocation.method(#getShiftNote, [shiftNoteId]),
              ),
            ),
          )
          as _i8.Future<_i7.ShiftNote>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getRecentShiftNotes({
    int? limit,
    String? clientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentShiftNotes, [], {
              #limit: limit,
              #clientId: clientId,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> listShiftNotes({
    String? clientId,
    String? stakeholderId,
    String? dateFrom,
    String? dateTo,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listShiftNotes, [], {
              #clientId: clientId,
              #stakeholderId: stakeholderId,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> createShiftNote({
    required String? clientId,
    required String? userId,
    required String? shiftDate,
    required String? startTime,
    required String? endTime,
    List<String>? primaryLocations,
    required String? rawNotes,
    List<String>? activityIds,
    List<Map<String, dynamic>>? goalsProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createShiftNote, [], {
              #clientId: clientId,
              #userId: userId,
              #shiftDate: shiftDate,
              #startTime: startTime,
              #endTime: endTime,
              #primaryLocations: primaryLocations,
              #rawNotes: rawNotes,
              #activityIds: activityIds,
              #goalsProgress: goalsProgress,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> updateShiftNote({
    required String? shiftNoteId,
    String? userId,
    String? shiftDate,
    String? startTime,
    String? endTime,
    List<String>? primaryLocations,
    String? rawNotes,
    List<String>? activityIds,
    List<Map<String, dynamic>>? goalsProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateShiftNote, [], {
              #shiftNoteId: shiftNoteId,
              #userId: userId,
              #shiftDate: shiftDate,
              #startTime: startTime,
              #endTime: endTime,
              #primaryLocations: primaryLocations,
              #rawNotes: rawNotes,
              #activityIds: activityIds,
              #goalsProgress: goalsProgress,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> deleteShiftNote(String? shiftNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteShiftNote, [shiftNoteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> submitShiftNote(String? shiftNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#submitShiftNote, [shiftNoteId]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> addActivitySessionToShiftNote({
    required String? shiftNoteId,
    required String? activitySessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addActivitySessionToShiftNote, [], {
              #shiftNoteId: shiftNoteId,
              #activitySessionId: activitySessionId,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getShiftNoteWithSessions(
    String? shiftNoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getShiftNoteWithSessions, [shiftNoteId]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<String> generateMediaUploadUrl() =>
      (super.noSuchMethod(
            Invocation.method(#generateMediaUploadUrl, []),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateMediaUploadUrl, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> addMediaToSession({
    required String? sessionId,
    required String? storageId,
    required String? type,
    required String? fileName,
    required int? fileSize,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMediaToSession, [], {
              #sessionId: sessionId,
              #storageId: storageId,
              #type: type,
              #fileName: fileName,
              #fileSize: fileSize,
              #mimeType: mimeType,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<String> getMediaFileUrl(String? storageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaFileUrl, [storageId]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getMediaFileUrl, [storageId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> removeMediaFromSession({
    required String? sessionId,
    required String? mediaId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMediaFromSession, [], {
              #sessionId: sessionId,
              #mediaId: mediaId,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);
}
