// Mocks generated by Mockito 5.4.6 from annotations
// in agnovat_w/test/unit/services/mcp_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:agnovat_w/core/services/convex_client_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConvexClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvexClientService extends _i1.Mock
    implements _i3.ConvexClientService {
  MockConvexClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<T> query<T>(String? functionName, {Map<String, dynamic>? args}) =>
      (super.noSuchMethod(
            Invocation.method(#query, [functionName], {#args: args}),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#query, [functionName], {#args: args}),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#query, [functionName], {#args: args}),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> mutation<T>(
    String? functionName, {
    Map<String, dynamic>? args,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mutation, [functionName], {#args: args}),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#mutation, [functionName], {#args: args}),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#mutation, [functionName], {#args: args}),
                ),
          )
          as _i2.Future<T>);
}
